---
title: "NYCsquirrels"
author: "Jeff Grayum"
date: "8/29/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries.
```{r}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggthemes)
library(ggmap)
library(sf)
```

Loading datasets.   
```{r}
nyc_squirrels <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-29/nyc_squirrels.csv")

nyc_squirrels %>%
  view()
```

Doing some stuff before watching the screencast.
```{r}
nyc_squirrels %>%
  count(unique_squirrel_id, sort = TRUE)

nyc_squirrels %>%
  filter(unique_squirrel_id %in% "1F-AM-1010-04") %>%
  view()

nyc_squirrels %>%
  count(highlight_fur_color, sort = TRUE)

nyc_squirrels %>%
  filter(!is.na(primary_fur_color),
         !is.na(highlight_fur_color)) %>%
  mutate(highlight_fur_color = fct_lump(highlight_fur_color, 4)) %>%
  count(primary_fur_color, highlight_fur_color) %>%
  mutate(primary_fur_color = fct_reorder(primary_fur_color, n, sum)) %>%
  ggplot(aes(n, primary_fur_color, fill = highlight_fur_color)) +
  geom_col() +
  scale_color_discrete() +
  labs(x = " ",
       y = "Primary fur color",
       fill = "Highlight fur color",
       title = "Colors of NYC squirrels") +
  theme_hc()

nyc_squirrels %>%
  filter(!is.na(primary_fur_color),
         !is.na(age),
         age != "?") %>%
  count(primary_fur_color, age) %>%
  mutate(primary_fur_color = fct_reorder(primary_fur_color, n, sum)) %>%
  ggplot(aes(n, primary_fur_color, fill = age)) +
  geom_col() +
  scale_color_discrete() +
  labs(x = " ",
       y = "Primary fur color",
       fill = "Age",
       title = "Primary colors of NYC squirrels") +
  theme_hc()

nyc_squirrels %>%
  filter(!is.na(specific_location)) %>%
  count(specific_location, sort = TRUE) %>%
  head(7) %>%
  mutate(specific_location = fct_reorder(specific_location, n)) %>%
  ggplot(aes(n, specific_location, fill = specific_location)) +
  geom_col() +
  labs(x = "",
       y = "Location seen",
       title = "Where we be seeing these squirrels?") +
  theme_hc() +
  theme(legend.position = "none")
```


Okidokie. Screencast time.
```{r}
nyc_squirrels %>%
  ggplot(aes(long, lat)) +
  geom_point() +
  theme_map()

by_hectare <- nyc_squirrels %>%
  filter(!is.na(primary_fur_color)) %>%
  group_by(hectare) %>%
  summarize(long = mean(long),
            lat = mean(lat),
            pct_gray = mean(primary_fur_color == "Gray", na.rm = TRUE),
            n = n()) 

by_hectare %>%
  ggplot(aes(long, lat, size = n)) +
  geom_point() +
  theme_map() +
  theme(legend.position = "right") +
  labs(title = "Squirrels in Central Park",
       size = "# squirrels/hectare")

nyc_squirrels %>%
  count(color_notes, sort = TRUE)

nyc_squirrels %>%
  count(primary_fur_color, sort = TRUE)

nyc_squirrels %>%
  count(primary_fur_color, highlight_fur_color, sort = TRUE)

by_hectare %>%
  filter(n >= 10) %>%
  ggplot(aes(long, lat, size = n, color = pct_gray)) +
  geom_point() +
  theme_map() +
  theme(legend.position = "right") +
  scale_color_gradient2(low = "blue", high = "red", mid = "pink", midpoint = 0.95, labels = scales::percent) +
  labs(size = "# squirrels",
       color = "# gray",
       title = "Are gray squirrels assosiated with any location in Central Park?")

by_hectare %>%
  filter(n >= 10) %>%
  ggplot(aes(lat, pct_gray)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Latitude",
       y = "% gray (primary fur color)",
       title = "How does primary color change with latitude?",
       subtitle = "Looking at squirells in Central Park") +
  theme_few()

by_hectare %>%
  filter(n >= 10) %>%
  ggplot(aes(long, pct_gray)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Longitude",
       y = "% gray (primary fur color)",
       title = "How does primary color change with longitude?",
       subtitle = "Looking at squirells in Central Park") +
  theme_few()

by_hectare %>%
  mutate(n_gray = round(pct_gray * n)) %>%
  glm(cbind(n_gray, n - n_gray) ~ lat, data = ., family = "binomial") %>%
  summary()

#Positive estimate (lat 23.058), with sig pvalue (3.81e -06), Squirrels more likely to be gray as you move north!

by_hectare %>%
  mutate(n_gray = round(pct_gray * n)) %>%
  glm(cbind(n_gray, n - n_gray) ~ long, data = ., family = "binomial") %>%
  summary()

#It seems like squirrels more likely to be gray as long increases, as well.


#Lets look at behavior.
nyc_squirrels %>%
  count(approaches, sort = TRUE)

nyc_squirrels %>%
  count(indifferent, sort = TRUE)

nyc_squirrels %>%
  count(runs_from, sort = TRUE)

nyc_squirrels %>%
  count(approaches, indifferent, runs_from, sort = TRUE)

#Is a squirrel run away as a function of latitude in the park?

glm(runs_from ~ lat, data = nyc_squirrels, family = "binomial") %>%
  summary()

by_hectare <- nyc_squirrels %>%
  add_count(hectare) %>%
  group_by(hectare, n) %>%
  summarize_at(vars(long, lat, runs_from, indifferent), mean) %>%
  ungroup() %>%
  filter(n >= 10) 

by_hectare %>%
  ggplot(aes(long, lat, size = n, color = runs_from)) +
  geom_point() +
  theme_map() +
  theme(legend.position = "right") +
  labs(size = "# squirrels",
       color = "% runs away",
       title = "Squirrels in the northwest corner of Central Park are more likely to run away",
       subtitle = "Central Park, NYC") +
  scale_color_gradient2(low = "blue", high = "red", mid = "pink",
                        midpoint = 0.3, labels = scales::percent)


                        

#Let's try making a ggmap!
by_hectare %>%
  head(1) %>%
  pull(long)

by_hectare %>%
  head(1) %>%
  pull(lat)

get_map(location = c(lon = -73.98, lat = 40.77))
#Google requires an API key.... we dont have time for that.  And we're at a logical stopping point for the day.
  

central_park_sf <- read_sf("~/Downloads/CentralAndProspectParks/")
#HOLY CRAP IT WORKED

ggplot(central_park_sf) +
  geom_sf()
#STUNNED

ggplot(central_park_sf) +
  geom_sf() +
  geom_point(aes(long, lat, size = n, color = runs_from), data = by_hectare) 

by_hectare %>%
  filter(n >= 10) %>%
  ggplot() +
  geom_sf(data = central_park_sf) +
  geom_point(aes(long, lat, size = n, color = runs_from)) +
  theme_map() +
  labs(size = "# squirrels",
       color = "% runs away",
       title = "Squirrels in the northwest corner of Central Park are more likely to run away",
       subtitle = "Central Park, NYC") +
  scale_color_gradient2(low = "blue", high = "red", mid = "pink",
                        midpoint = 0.3, labels = scales::percent) +
  theme(legend.position = "right") +
  coord_sf(datum = NA)

central_park_sf %>%
  summary()
 
  
central_park_sf %>%
  ggplot() +
  geom_sf(aes(color = bicycle))

central_park_sf %>%
  ggplot() +
  geom_sf(aes(color = foot))
```


```{r}
nyc_squirrels %>%
  count(other_activities, sort = TRUE, name = "# squirrels")

nyc_squirrels %>%
  select(ends_with("ing"))

nyc_squirrels %>%
  gather(activity, doing, ends_with("ing")) %>%
  view()

nyc_squirrels %>%
  gather(activity, doing, ends_with("ing")) %>%
  filter(doing) %>%
  count(activity, sort = TRUE)

by_hectare <- nyc_squirrels %>%
  add_count(hectare) %>%
  group_by(hectare, n) %>%
  summarize_at(vars(long, lat, approaches:runs_from, indifferent, ends_with("ing")), mean) %>%
  ungroup()
```

Let's make a shiny app. 
OK, we made a shiny app.

Lets check some distributions
```{r}
by_hectare %>%
  gather(variable, value, kuks:foraging) %>%
  filter(n >= 10) %>%
  ggplot(aes(value)) +
  geom_histogram() +
  facet_wrap(~variable)

A lot of zeros...
```

